# Label StoreMax
# Version 2.1.0
#authors: - "Anthony Gordon"
#documentation: https://woosignal.com/docs/app/ios/label-storemax
#homepage: https://woosignal.com/

### App Config
# 1 Open: "lib/labelconfig.dart"

### Change App Icon
# 1 Replace: assets/icon/appicon.png (1024px1024px icon size)
# 2 Run this command from Terminal: flutter pub run flutter_launcher_icons:main

### Uploading the IOS/Android app
# IOS https://flutter.dev/docs/deployment/ios
# Android https://flutter.dev/docs/deployment/android

name: label_storemax
description: LabelStoreMAX

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  woosignal: ^1.1.2
  woosignal_stripe: ^0.0.6
  razorpay_flutter: ^1.2.2
  wp_json_api: ^0.1.4
  shared_preferences: ^0.5.7+3
  cached_network_image: ^2.2.0+1
  page_transition: ^1.1.5
  package_info: ^0.4.0+16
  url_launcher: ^5.4.11
  flutter_money_formatter: ^0.8.3
  platform_alert_dialog: ^1.0.0+2
  flutter_web_browser: ^0.11.0
  pull_to_refresh: ^1.5.8
  intl: ^0.16.1
  flutter_swiper: ^1.1.6
  edge_alert: ^0.0.1
  bubble_tab_indicator: ^0.1.4
  status_alert: ^0.1.2
  math_expressions: ^2.0.0
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.7.5
  auto_size_text: ^2.1.0
  html: ^0.14.0+3
  flutter_staggered_grid_view: ^0.3.1
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon.png"

dependency_overrides:
  intl:

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/camion.gif
    - assets/images/credit_cards.png
    - assets/images/shipping_icon.png
    - assets/images/dark_powered_by_stripe.png
    - assets/images/cash_on_delivery.jpeg
    - assets/images/razorpay.png
    - lang/en.json
    - lang/es.json
    - lang/fr.json
    - lang/it.json
    - lang/de.json
    - lang/hi.json
    - lang/pt.json

  fonts:
     - family: Overpass
       fonts:
         - asset: assets/fonts/Overpass/Overpass-Regular.ttf
