# Official WooSignal App Template for WooCommerce

# Label StoreMax
# Version 3.0.0
# Homepage: https://woosignal.com
# Author: Anthony Gordon <agordon@woosignal.com>
# Documentation: https://woosignal.com/docs/app/ios/label-storemax

### Change App Icon
# 1 Replace: assets/icon/appicon.png (1024px1024px icon size)
# 2 Run this command from the terminal: "flutter pub run flutter_launcher_icons:main"

### Uploading the IOS/Android app
# IOS https://flutter.dev/docs/deployment/ios
# Android https://flutter.dev/docs/deployment/android

name: label_storemax
description: LabelStoreMAX

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  woosignal: ^1.4.0
  woosignal_stripe: ^0.1.0
  razorpay_flutter: 1.2.3
  wp_json_api: ^2.0.0
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.5.0
  page_transition: ^1.1.7+6
  package_info: ^0.4.3+2
  url_launcher: ^5.7.10
  flutter_money_formatter: ^0.8.3
  platform_alert_dialog: ^1.0.0+2
  flutter_web_browser: ^0.13.1
  pull_to_refresh: 1.6.4
  intl: ^0.17.0
  flutter_swiper: ^1.1.6
  edge_alert: ^0.0.1
  bubble_tab_indicator: ^0.1.4
  status_alert: ^0.1.3
  math_expressions: ^2.0.2
  hexcolor: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.8.1
  auto_size_text: ^2.1.0
  html: ^0.14.0+4
  flutter_staggered_grid_view: ^0.3.4
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_application_id: "^1.0.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon.png"

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/camion.gif
    - assets/images/credit_cards.png
    - assets/images/shipping_icon.png
    - assets/images/dark_powered_by_stripe.png
    - assets/images/cash_on_delivery.jpeg
    - assets/images/razorpay.png
    - assets/default_shipping.json
    - lang/en.json
    - lang/es.json
    - lang/fr.json
    - lang/it.json
    - lang/de.json
    - lang/hi.json
    - lang/pt.json

  fonts:
     - family: Overpass
       fonts:
         - asset: assets/fonts/Overpass/Overpass-Regular.ttf
