# Label StoreMax
# Version 1.0
#authors: - "Anthony Gordon"
#documentation: https://woosignal.com/docs/app/ios/label-storemax
#homepage: https://woosignal.com/

### App Config
# 1 Open: "lib/labelconfig.dart"

### Change App Icon
# 1 Open: assets/icon/appicon.png (line 53) replace icon (1024px1024px icon size)
# 2 Run this command from Terminal: flutter pub run flutter_launcher_icons:main

### Submitting the IOS/Android app
# 1 Open our online documentation: https://woosignal.com/docs/app/ios/label-storemax

name: label_storemax
description: LabelStoreMAX

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  woosignal: ^1.0.2
  woosignal_stripe: ^0.0.2
  connectivity: ^0.4.4
  shared_preferences: ^0.5.3+4
  cached_network_image: ^1.1.1
  page_transition: ^1.1.4
  package_info: ^0.4.0+6
  flutter_money_formatter: ^0.8.2
  flutter_web_browser: ^0.11.0
  dio: ^3.0.2
  flutter_swiper: ^1.1.6
  edge_alert: ^0.0.1
  fluttertoast: ^3.1.3
  flutter_spinkit: ^4.0.0
  pref_dessert: ^0.4.0+1
  flutter_launcher_icons: ^0.7.3
  html: ^0.14.0+3
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon.png"
  
dependency_overrides:
  intl:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/camion.gif
    - assets/images/credit_cards.png
    - assets/images/shipping_icon.png
    - assets/images/dark_powered_by_stripe.png
    - assets/images/cart_empty.png
    - lang/en.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
     - family: Overpass
       fonts:
         - asset: assets/fonts/Overpass/Overpass-Regular.ttf
