# Label StoreMax
# Version 2.0.0
#authors: - "Anthony Gordon"
#documentation: https://woosignal.com/docs/app/ios/label-storemax
#homepage: https://woosignal.com/

### App Config
# 1 Open: "lib/labelconfig.dart"

### Change App Icon
# 1 Open: assets/icon/appicon.png (line 53) replace icon (1024px1024px icon size)
# 2 Run this command from Terminal: flutter pub run flutter_launcher_icons:main

### Submitting the IOS/Android app
# 1 Open our online documentation: https://woosignal.com/docs/app/ios/label-storemax

name: label_storemax
description: LabelStoreMAX

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  woosignal: ^1.0.6
  woosignal_stripe: ^0.0.4
  wp_json_api: ^0.1.1
  shared_preferences: ^0.5.6+3
  cached_network_image: ^2.0.0
  page_transition: ^1.1.5
  package_info: ^0.4.0+16
  url_launcher: ^5.4.5
  flutter_money_formatter: ^0.8.3
  platform_alert_dialog: ^1.0.0+2
  flutter_web_browser: ^0.11.0
  dio: ^3.0.9
  intl: ^0.16.1
  flutter_swiper: ^1.1.6
  edge_alert: ^0.0.1
  bubble_tab_indicator: ^0.1.4
  status_alert: ^0.1.1
  math_expressions: ^2.0.0
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.7.4
  html: ^0.14.0+3
  braintree_payment: ^1.2.4
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon.png"

dependency_overrides:
  intl:

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/camion.gif
    - assets/images/credit_cards.png
    - assets/images/shipping_icon.png
    - assets/images/dark_powered_by_stripe.png
    - assets/images/cart_empty.png
    - lang/en.json

  fonts:
     - family: Overpass
       fonts:
         - asset: assets/fonts/Overpass/Overpass-Regular.ttf
